'use strict';

let _trm=document.querySelectorAll("ul>li>code");
    _trm[0].onclick=()=>alert("storage permission");
    _trm[1].onclick=()=>alert("clear all text");
    _trm[2].onclick=()=>alert("for apt update");
    _trm[3].onclick=()=>alert("for apt upgrade");
    _trm[4].onclick=()=>alert("leave from app");
    _trm[5].onclick=()=>alert("default tools");
    _trm[6].onclick=()=>alert("for install package");
    _trm[7].onclick=()=>alert("for install package");
    _trm[8].onclick=()=>alert("remove package");
    _trm[9].onclick=()=>alert("show pkg details ");
    _trm[10].onclick=()=>alert("internal storage");
    _trm[11].onclick=()=>alert("list of folder and file");
    _trm[12].onclick=()=>alert("list of hidden file and folder");
    _trm[13].onclick=()=>alert("file or folder details");
    _trm[14].onclick=()=>alert("create file");
    _trm[15].onclick=()=>alert("to see a file");
    _trm[16].onclick=()=>alert("write a file");
    _trm[17].onclick=()=>alert("present working directory");
    _trm[18].onclick=()=>alert("create folder");
    _trm[19].onclick=()=>alert("enter the folder");
    _trm[20].onclick=()=>alert("back from the folder");
    _trm[21].onclick=()=>alert("back to home");
    _trm[22].onclick=()=>alert("copy file");
    _trm[23].onclick=()=>alert("copy folder");
    _trm[24].onclick=()=>alert("move file");
    _trm[25].onclick=()=>alert("move folder");
    _trm[26].onclick=()=>alert("delete file");
    _trm[27].onclick=()=>alert("remove folder");
    _trm[28].onclick=()=>alert("create a text file");
    _trm[29].onclick=()=>alert("hide file");
    _trm[30].onclick=()=>alert("create localhost");
